main: me.snowman.prename.ItemRename
author: SnowmanFTW
version: 1.4.1
api-version: 1.13
name: ItemRename
softdepend: [Vault]
commands:
  itemrename:
    description: Main command
    aliases: [irename, ir]
  rename:
    description: Rename command
  colorize:
    description: Colorize command